### ISSUE TITLE
[Bug]: Killing the server while the instance is created breaks `process_runs`

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#1079]
### Steps to reproduce

1. Submit a run.
2. Kill the server while the create_instance is execution.
3. Start the server again. The `process_runs` task starts to raise `AttributeError`, effectively breaking the server.

### dstack version

master

### Server logs

```shell
ERROR 2024-04-02T16:34:07.611 apscheduler.executors.default Job "process_runs (trigger: interval[0:00:01], next run at: 2024-04-02 16:34:08 +05)" raised an exception
Traceback (most recent call last):
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/background/tasks/process_runs.py", line 70, in process_runs
    run_id = await future
             ^^^^^^^^^^^^
  File "/Users/r4victor/.pyenv/versions/3.11.2/lib/python3.11/asyncio/tasks.py", line 605, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/background/tasks/process_runs.py", line 96, in process_single_run
    await process_active_run(session, run)
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/background/tasks/process_runs.py", line 220, in process_active_run
    if await is_retry_enabled(session, job, retry_policy):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/background/tasks/process_runs.py", line 325, in is_retry_enabled
    if instance_offer.instance.resources.spot:
                                               
AttributeError: 'NoneType' object has no attribute 'offer'
```

**Comment by peterschmidt85** [comment]
Sounds as a major problem. We promise users that restarting servers won't affect their runs. Is it easy to fix? Shall we do a hot-fix?

**Comment by peterschmidt85** [comment]
Or it affects only the runs that were pending on creating new instances?
