### ISSUE TITLE
[Bug]: Permission denied: `/Users/riwaj/.ssh/config.lock`

### ISSUE THREAD

**Issue by riwajsapkota** [dstackai/dstack#1205]
### Steps to reproduce

1. `dstack run . -f examples/.dstack.yml`

### Actual behaviour

```
dstack run . -f examples/.dstack.yml 
 Configuration          examples/.dstack.yml                         
 Project                hse-demo                                     
 User                   riwajsapkota                                 
 Pool name              default-pool                                 
 Min resources          2..xCPU, 8GB.., 1xGPU (24GB), 100GB.. (disk) 
 Max price              -                                            
 Max duration           6h                                           
 Spot policy            on-demand                                    
 Retry policy           no                                           
 Creation policy        reuse-or-create                              
 Termination policy     destroy-after-idle                           
 Termination idle time  300s                                         

 #  BACKEND     REGION        INSTANCE                              RESOURCES                                    SPOT  PRICE    
 1  tensordock  unitedstates  b791e1d7-e21e-47e6-b6dd-4ef20b27119b  2xCPU, 10GB, 1xRTX3090 (24GB), 100GB (disk)  no    $0.231   
 2  tensordock  india         6f0185aa-4561-426f-a6e6-cce86dca2bd1  8xCPU, 48GB, 1xA5000 (24GB), 100GB (disk)    no    $0.335   
 3  tensordock  spain         c436b1f4-11fc-45ec-8499-687e80313540  8xCPU, 38GB, 1xRTX3090 (24GB), 100GB (disk)  no    $0.335   
    ...                                                                                                                         
 Shown 3 of 140 offers, $5.876 max

Continue? [y/n]: y
tame-shrimp-1 provisioning completed (running)
Aborted
Traceback (most recent call last):
  File "/opt/anaconda3/bin/dstack", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.9/site-packages/dstack/_internal/cli/main.py", line 67, in main
    args.func(args)
  File "/opt/anaconda3/lib/python3.9/site-packages/dstack/_internal/cli/commands/run.py", line 183, in _command
    if run.attach():
  File "/opt/anaconda3/lib/python3.9/site-packages/dstack/api/_public/runs.py", line 293, in attach
    self._ssh_attach.attach()
  File "/opt/anaconda3/lib/python3.9/site-packages/dstack/_internal/core/services/ssh/attach.py", line 114, in attach
    include_ssh_config(self.ssh_config_path)
  File "/opt/anaconda3/lib/python3.9/site-packages/dstack/_internal/utils/ssh.py", line 61, in include_ssh_config
    with FileLock(str(ssh_config_path) + ".lock"):
  File "/opt/anaconda3/lib/python3.9/site-packages/filelock/_api.py", line 214, in __enter__
    self.acquire()
  File "/opt/anaconda3/lib/python3.9/site-packages/filelock/_api.py", line 170, in acquire
    self._acquire()
  File "/opt/anaconda3/lib/python3.9/site-packages/filelock/_unix.py", line 35, in _acquire
    fd = os.open(self._lock_file, open_mode)
PermissionError: [Errno 13] Permission denied: '/Users/riwaj/.ssh/config.lock'
```

### dstack version

0.18.1

**Comment by riwajsapkota** [comment]
`sudo chmod -R 700 /Users/riwaj/.ssh/`helped

**Comment by peterschmidt85** [comment]
I faced the same issue myself just today. I think we could check it before provisioning...

**Comment by peterschmidt85** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by peterschmidt85** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale. Please reopen the issue if it is still relevant.

**Comment by Janinanu** [comment]
Please reopen the issue. I got into it.
1. The check must be done before provisioning.
2. The run remained running and I only noticed it much later

**Comment by easedeath** [comment]
Hi can I work on this issue?
