### ISSUE TITLE
[Bug]: Gateway creation fails on GCP

### ISSUE THREAD

**Issue by 0xSMW** [dstackai/dstack#1207]
### Steps to reproduce

<img width="652" alt="image" src="https://github.com/dstackai/dstack/assets/12349/59cb2f5b-98ed-4c1e-885b-b32a19d06455">

`dstack gateway create --domain domain.net --region us-central-1 --backend gcp`

### dstack version

0.18.1

### Server logs

```shell
Error dump: 

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/dstack/_internal/server/app.py", line 195, in check_client_version
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/dstack/_internal/server/app.py", line 175, in log_request
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/dstack/_internal/server/routers/gateways.py", line 46, in create_gateway
    return await gateways.create_gateway(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/dstack/_internal/server/services/gateways/__init__.py", line 144, in create_gateway
    gateway.gateway_compute = await create_gateway_compute(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/dstack/_internal/server/services/gateways/__init__.py", line 96, in create_gateway_compute
    info = await run_async(
           ^^^^^^^^^^^^^^^^
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/dstack/_internal/server/utils/common.py", line 24, in run_async
    return await asyncio.get_running_loop().run_in_executor(None, func_with_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephenwalker/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stephenwalker/anaconda3/lib/python3.11/site-packages/dstack/_internal/core/backends/gcp/compute.py", line 195, in create_gateway
    raise ComputeResourceNotFoundError()
dstack._internal.core.errors.ComputeResourceNotFoundError
```

**Comment by peterschmidt85** [comment]
I confirm that I reproduced it! Thank you @0xSMW for reporting. The fix is on the way.

**Comment by peterschmidt85** [comment]
@0xSMW Just noticed that the error is caused by the wrong name of the region. It should be `us-central1`. 
I think we should improve error handling.
Plese confirm.

**Comment by 0xSMW** [comment]
ah you're right, works with the right region name
