### ISSUE TITLE
If the repo has no commits, the CLI doesn't work

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#134]
Steps to reproduce:

1. Create a new repo on GitHub
2. Clone this repo
3. Create a workflow file (e.g. `.dstack/workflows/test.yaml`
4. Run your workflow with `dstack run` 

Expectation: 
1. It works

Reality:

1. It throws the following error:

```
Traceback (most recent call last):
  File "/Users/cheptsov/opt/anaconda3/bin/dstack", line 8, in <module>
    sys.exit(main())
  File "/Users/cheptsov/opt/anaconda3/lib/python3.9/site-packages/dstack/cli/main.py", line 77, in main
    args.func(args)
  File "/Users/cheptsov/opt/anaconda3/lib/python3.9/site-packages/dstack/cli/run.py", line 195, in run_workflow_func
    repo_data = load_repo_data()
  File "/Users/cheptsov/opt/anaconda3/lib/python3.9/site-packages/dstack/repo.py", line 128, in load_repo_data
    repo_hash = tracking_branch.commit.hexsha
  File "/Users/cheptsov/opt/anaconda3/lib/python3.9/site-packages/git/refs/symbolic.py", line 217, in _get_commit
    obj = self._get_object()
  File "/Users/cheptsov/opt/anaconda3/lib/python3.9/site-packages/git/refs/symbolic.py", line 210, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/Users/cheptsov/opt/anaconda3/lib/python3.9/site-packages/git/refs/symbolic.py", line 151, in dereference_recursive
    hexsha, ref_path = cls._get_ref_info(repo, ref_path)
  File "/Users/cheptsov/opt/anaconda3/lib/python3.9/site-packages/git/refs/symbolic.py", line 201, in _get_ref_info
    return cls._get_ref_info_helper(repo, ref_path)
  File "/Users/cheptsov/opt/anaconda3/lib/python3.9/site-packages/git/refs/symbolic.py", line 184, in _get_ref_info_helper
    raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at 'refs/remotes/origin/main' does not exist
```

**Comment by peterschmidt85** [comment]
Related issue: Better handle "No tracked branch configured for branch dstack” #63

**Comment by peterschmidt85** [comment]
cc @c0stya
