### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/Users/deep-diver/.dstack/ssh/config'

### ISSUE THREAD

**Issue by deep-diver** [dstackai/dstack#1719]
### Steps to reproduce

1. Successfully created `ssh-fleet`.
2. Create a `test.dstack.yml` with the following contents.
```yaml
type: dev-environment
ide: vscode
```
3. Run `dstack apply -f test.dstack.yml`

### Actual behaviour (1)

After passing `y` to the prompt, I get the following error.

I did the followings to try to fix, but no use so far.
- `$ sudo chmod -R 700 /Users/deep-diver/.dstack/`
- `$ sudo chmod -R 700 /Users/deep-diver/.ssh`

```
Unable to detect the VS Code version and pre-install extensions. Fix by opening Command Palette, executing Shell Command: Install 'code' command in 
PATH, and restarting terminal.

 Configuration          dev.dstack.yml                 
 Project                main                           
 User                   admin                          
 Pool                   default-pool                   
 Min resources          2..xCPU, 8GB.., 100GB.. (disk) 
 Max price              -                              
 Max duration           6h                             
 Spot policy            auto                           
 Retry policy           no                             
 Creation policy        reuse-or-create                
 Termination policy     destroy-after-idle             
 Termination idle time  5m                             

 #  BACKEND  REGION  INSTANCE  RESOURCES                                            SPOT  PRICE       
 1  ssh      remote  instance  32xCPU, 503GB, 3xRTX6000Ada (48GB), 1534.8GB (disk)  no    $0     idle 
 2  ssh      remote  instance  32xCPU, 503GB, 3xRTX6000Ada (48GB), 1659.3GB (disk)  no    $0     idle 
 3  ssh      remote  instance  64xCPU, 693GB, 2xA6000 (48GB), 1683.7GB (disk)       no    $0     idle 
    ...                                                                                               
 Shown 3 of 4 offers, $0 max

Submit the run vscode? [y/n]: y
vscode provisioning completed (running)
Traceback (most recent call last):
  File "/Users/deep-diver/opt/miniconda3/envs/dstack/lib/python3.11/site-packages/dstack/_internal/cli/services/configurators/run.py", line 147, in apply_configuration
    if run.attach(bind_address=bind_address):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deep-diver/opt/miniconda3/envs/dstack/lib/python3.11/site-packages/dstack/api/_public/runs.py", line 288, in attach
    self._ssh_attach.attach()
  File "/Users/deep-diver/opt/miniconda3/envs/dstack/lib/python3.11/site-packages/dstack/_internal/core/services/ssh/attach.py", line 170, in attach
    update_ssh_config(self.ssh_config_path, f"{self.run_name}-host", self.host_config)
  File "/Users/deep-diver/opt/miniconda3/envs/dstack/lib/python3.11/site-packages/dstack/_internal/utils/ssh.py", line 168, in update_ssh_config
    with open(path, "r") as f:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/Users/deep-diver/.dstack/ssh/config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/deep-diver/opt/miniconda3/envs/dstack/lib/python3.11/site-packages/dstack/_internal/cli/services/configurators/run.py", line 155, in apply_configuration
    run.detach()
  File "/Users/deep-diver/opt/miniconda3/envs/dstack/lib/python3.11/site-packages/dstack/api/_public/runs.py", line 299, in detach
    self._ssh_attach.detach()
  File "/Users/deep-diver/opt/miniconda3/envs/dstack/lib/python3.11/site-packages/dstack/_internal/core/services/ssh/attach.py", line 189, in detach
    update_ssh_config(self.ssh_config_path, f"{self.run_name}-jump-host", {})
  File "/Users/deep-diver/opt/miniconda3/envs/dstack/lib/python3.11/site-packages/dstack/_internal/utils/ssh.py", line 168, in update_ssh_config
    with open(path, "r") as f:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/Users/deep-diver/.dstack/ssh/config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/deep-diver/opt/miniconda3/envs/dstack/bin/dstack", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/deep-diver/opt/miniconda3/envs/dstack/lib/python3.11/site-packages/dstack/_internal/cli/main.py", line 77, in main
    args.func(args)
  File "/Users/deep-diver/opt/miniconda3/envs/dstack/lib/python3.11/site-packages/dstack/_internal/cli/commands/apply.py", line 70, in _command
    configurator.apply_configuration(
  File "/Users/deep-diver/opt/miniconda3/envs/dstack/lib/python3.11/site-packages/dstack/_internal/cli/services/configurators/run.py", line 192, in apply_configuration
    run.detach()
  File "/Users/deep-diver/opt/miniconda3/envs/dstack/lib/python3.11/site-packages/dstack/api/_public/runs.py", line 299, in detach
    self._ssh_attach.detach()
  File "/Users/deep-diver/opt/miniconda3/envs/dstack/lib/python3.11/site-packages/dstack/_internal/core/services/ssh/attach.py", line 189, in detach
    update_ssh_config(self.ssh_config_path, f"{self.run_name}-jump-host", {})
  File "/Users/deep-diver/opt/miniconda3/envs/dstack/lib/python3.11/site-packages/dstack/_internal/utils/ssh.py", line 168, in update_ssh_config
    with open(path, "r") as f:
         ^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/Users/deep-diver/.dstack/ssh/config'
```

and this is the logs from the `dstack server` side
```
[15:26:09] WARNING  dstack._internal.server.services.backends:271 Missing dependencies for gcp backend. Backend will be ignored.                      
           INFO     dstack._internal.server.services.backends:404 Requesting instance offers from backends: []                                        
[15:26:12] WARNING  dstack._internal.server.services.backends:271 Missing dependencies for gcp backend. Backend will be ignored.                      
           INFO     dstack._internal.server.services.backends:404 Requesting instance offers from backends: []                                        
[15:26:23] INFO     dstack._internal.server.background.tasks.process_submitted_jobs:333 The job vscode-0-0 switched instance my-ssh-fleet-0 status to 
                    BUSY                                                                                                                              
           INFO     dstack._internal.server.background.tasks.process_submitted_jobs:342 job(176669)vscode-0-0: now is provisioning on 'my-ssh-fleet-0'
[15:26:29] INFO     dstack._internal.server.background.tasks.process_runs:330 run(a0aed0)vscode: run status has changed SUBMITTED -> PROVISIONING     
[15:26:32] INFO     dstack._internal.server.background.tasks.process_running_jobs:411 job(176669)vscode-0-0: now is PULLING                           
[15:26:37] INFO     dstack._internal.server.background.tasks.process_runs:330 run(a0aed0)vscode: run status has changed PROVISIONING -> RUNNING                                                             
[15:26:42] INFO     dstack._internal.server.background.tasks.process_running_jobs:519 job(176669)vscode-0-0: now is RUNNING 
```

### Actual behaviour (2)

I tried out with `sudo` permissions as
: `sudo dstack apply -f ...`

then I got the following behaviors that keep asking the password of the remote server. when creating `ssh-fleet` with `id_rsa`, it didn't ask any password (so I assume ssh with `id_rsa` works correctly).

![ezgif-3-0b5fbfb092](https://github.com/user-attachments/assets/e1dc0c8f-42d4-4ceb-bdb3-a2f1e5fdc2a0)

Note that the GIF shows "enter password" multiple times even though I did not enter anything. It just keeps showing the new lines until the timeout.

### dstack version

0.18.14

### Additional information

When inspecting the logs from the server, the status of the run is `RUNNING` without being terminated.

Hence, I assume that this is an issue when the remote server sends the logs to the local environment.

**Comment by un-def** [comment]
@deep-diver could you provide `ls -l  ~/.dstack` and `ls -l  ~/.dstack/ssh` output?

**Comment by deep-diver** [comment]
```console
(dstack) deep-diver@deepdiverui-Mac-Studio dstack-fleet % ls -l  ~/.dstack
total 24
-rwx------  1 deep-diver  staff  408 Sep 24 09:21 config.yml
-rwx------  1 deep-diver  staff    0 Sep 24 09:21 config.yml.lock
-rwx------  1 deep-diver  staff  304 Sep 24 09:16 dstack.yml
-rwx------  1 deep-diver  staff  304 Sep 24 09:19 fleet.dstack.yml
drwx------  4 deep-diver  staff  128 Aug 25  2023 repos
drwx------  7 deep-diver  staff  224 Jun  4 07:30 server
drwx------  6 deep-diver  staff  192 Sep 24 13:45 ssh
```

```console
(dstack) deep-diver@deepdiverui-Mac-Studio dstack-fleet % ls -l  ~/.dstack/ssh
total 16
-rwx------  1 root        staff     0 Sep 24 13:55 config
-rw-r--r--  1 deep-diver  staff     0 Sep 24 15:26 config.lock
-rwx------  1 deep-diver  staff  1708 Aug 25  2023 id_rsa
-rwx------  1 deep-diver  staff   388 Aug 25  2023 id_rsa.pub
```

**Comment by deep-diver** [comment]
seems like `~/.dstack/ssh/config` is created and managed by `root` user somehow even though `~/.dstack/ssh` directory is under control by `deep-diver`. How is this possible?

**Comment by deep-diver** [comment]
removing `config` worked. This is my bad since I ran `dstack` within `sudo` mode a while ago and forgot about it. Sorry for bothering!
