### ISSUE TITLE
[Feature] Cannot get a plan of a run via the API if repo is not assigned

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1737]
**Steps to reproduce:**

```
from dstack.api import Client, Service

if __name__ == "__main__":
    client = Client.from_config()

    service = Service(
        image="python:3.11",
        commands=[
            "pip3 install streamlit",
            "streamlit hello",
        ],
        port="8501",
        spot_policy="auto",
        auth=False,
    )

    plan = client.runs.get_plan(
        run_name="my-first-service",  # If not specified, a random name is assigned
        configuration=service,
        repo=None,  # Specify to mount additional files
    )

    print(plan)
```

**Actual result:**

```
Traceback (most recent call last):
  File "/Users/cheptsov/Library/Application Support/JetBrains/PyCharm2024.3/scratches/scratch_144.py", line 19, in <module>
    plan = client.runs.get_plan(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/dstack/src/dstack/api/_public/runs.py", line 475, in get_plan
    repo_id=repo.repo_id,
            ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'repo_id'

Process finished with exit code 1
```

**Comment by r4victor** [comment]
@peterschmidt85 Apparently, `get_plan()` always required a repo. So it's a missing feature rather than an introduced bug.
