### ISSUE TITLE
[Bug]: dstack server prints exceptions on KeyboardInterrupt

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#492]
### dstack version

master

### Python version

3.11

### Host OS

macOS 13.4

### Host Arch

ARM

### What happened?

dstack server prints the traceback of `asyncio.exceptions.CancelledError` on ctrl+c that comes from `apscheduler` background job. The server should not print CancelledError on ctrl+c.

Related, sometimes ctrl+c may not exit the server, so you have to kill the process to exit it.

### Relevant log output

```shell
The server is available at http://127.0.0.1:3000?token=token
^CERROR 2023-06-19T13:59:57.228 apscheduler.executors.default Job "resubmit_jobs (trigger: interval[0:00:05], next run at: 2023-06-19 14:00:00 +05)" raised an exception
Traceback (most recent call last):
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/cli/dstack/_internal/hub/background/tasks/resubmit_jobs.py", line 16, in resubmit_jobs
    await _resubmit_projects_jobs(projects)
  File "/Users/r4victor/Projects/dstack/dstack/cli/dstack/_internal/hub/background/tasks/resubmit_jobs.py", line 21, in _resubmit_projects_jobs
    backend = await get_backend(project)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/cli/dstack/_internal/hub/routers/cache.py", line 25, in get_backend
    backend = await run_async(backend_cls, config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/cli/dstack/_internal/hub/utils/common.py", line 5, in run_async
    return await asyncio.get_running_loop().run_in_executor(None, func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError
```

**Comment by r4victor** [comment]
```
The server is available at http://127.0.0.1:3000?token=token
^CERROR 2023-06-19T13:59:57.228 apscheduler.executors.default Job "resubmit_jobs (trigger: interval[0:00:05], next run at: 2023-06-19 14:00:00 +05)" raised an exception
Traceback (most recent call last):
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/cli/dstack/_internal/hub/background/tasks/resubmit_jobs.py", line 16, in resubmit_jobs
    await _resubmit_projects_jobs(projects)
  File "/Users/r4victor/Projects/dstack/dstack/cli/dstack/_internal/hub/background/tasks/resubmit_jobs.py", line 21, in _resubmit_projects_jobs
    backend = await get_backend(project)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/cli/dstack/_internal/hub/routers/cache.py", line 25, in get_backend
    backend = await run_async(backend_cls, config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/cli/dstack/_internal/hub/utils/common.py", line 5, in run_async
    return await asyncio.get_running_loop().run_in_executor(None, func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError
(venv) ➜  dstack git:(master) ✗ dstack start
The server is available at http://127.0.0.1:3000?token=47e6aecd-ed30-47a8-8e96-773d3670bc79
^CERROR 2023-06-19T14:16:54.636 apscheduler.executors.default Job "resubmit_jobs (trigger: interval[0:00:05], next run at: 2023-06-19 14:16:57 +05)" raised an exception
Traceback (most recent call last):
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/cli/dstack/_internal/hub/background/tasks/resubmit_jobs.py", line 16, in resubmit_jobs
    await _resubmit_projects_jobs(projects)
  File "/Users/r4victor/Projects/dstack/dstack/cli/dstack/_internal/hub/background/tasks/resubmit_jobs.py", line 22, in _resubmit_projects_jobs
    await run_async(_resubmit_backend_jobs, backend)
  File "/Users/r4victor/Projects/dstack/dstack/cli/dstack/_internal/hub/utils/common.py", line 5, in run_async
    return await asyncio.get_running_loop().run_in_executor(None, func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError
ERROR 2023-06-19T14:16:57.996 apscheduler.executors.default Job "resubmit_jobs (trigger: interval[0:00:05], next run at: 2023-06-19 14:17:02 +05)" raised an exception
Traceback (most recent call last):
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/cli/dstack/_internal/hub/background/tasks/resubmit_jobs.py", line 16, in resubmit_jobs
    await _resubmit_projects_jobs(projects)
  File "/Users/r4victor/Projects/dstack/dstack/cli/dstack/_internal/hub/background/tasks/resubmit_jobs.py", line 22, in _resubmit_projects_jobs
    await run_async(_resubmit_backend_jobs, backend)
  File "/Users/r4victor/Projects/dstack/dstack/cli/dstack/_internal/hub/utils/common.py", line 5, in run_async
    return await asyncio.get_running_loop().run_in_executor(None, func, *args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 2724, in uvloop.loop.Loop.run_in_executor
  File "uvloop/loop.pyx", line 3161, in uvloop.loop.Loop._check_default_executor
RuntimeError: Executor shutdown has been called
```
