### ISSUE TITLE
Docker error on mac 

### ISSUE THREAD

**Issue by dhanush-2501** [dstackai/dstack#549]
**Getting Docker error while running examples provided in the docs** 
# System Details
- Os: Mac Os ventura 13.4.1
- CPU: Apple M1

# Steps to reproduce the error 
- step 1 - `cd dstack-examples`
- step 2 - `dstack start`
- step 3 - `dstack init`
- step 4 - `dstack run .` (or any other `dstack run` command provided in the examples)

# Error Details
- The server is available at http://127.0.0.1:3000?token=f8b768a1-184d-4127-803b-706193c4b9e3
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/dhanush/Library/Python/3.10/lib/python/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/Users/dhanush/Library/Python/3.10/lib/python/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "/Users/dhanush/Library/Python/3.10/lib/python/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/homebrew/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/opt/homebrew/lib/python3.10/site-packages/dstack/_internal/hub/main.py", line 77, in app_logging
    response = await call_next(request)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/homebrew/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/opt/homebrew/lib/python3.10/site-packages/dstack/_internal/hub/routers/runs.py", line 31, in get_run_plan
    instance_type = await run_async(backend.predict_instance_type, job)
  File "/opt/homebrew/lib/python3.10/site-packages/dstack/_internal/hub/utils/common.py", line 5, in run_async
    return await asyncio.get_running_loop().run_in_executor(None, func, *args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/dstack/_internal/backend/base/__init__.py", line 259, in predict_instance_type
    return base_jobs.predict_job_instance(self.compute(), job)
  File "/opt/homebrew/lib/python3.10/site-packages/dstack/_internal/backend/base/jobs.py", line 95, in predict_job_instance
    return compute.get_instance_type(job)
  File "/opt/homebrew/lib/python3.10/site-packages/dstack/_internal/backend/local/compute.py", line 20, in get_instance_type
    resources = runners.check_runner_resources(self.backend_config, job.runner_id)
  File "/opt/homebrew/lib/python3.10/site-packages/dstack/_internal/backend/local/runners.py", line 58, in check_runner_resources
    raise Exception(result.stderr)
Exception: time=2023-07-08T17:20:07.489571+05:30 level=error msg=Failed fetch info about client err=Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Docker is not installed

- `dstack run .`
Got 500 Server Error from hub: 
http://127.0.0.1:3000/api/project/local/runs/get_plan. Check hub 
logs for details.

# Docker terminal outputs
- \# : ls -l /var/run/docker.sock
ls: /var/run/docker.sock: No such file or directory

-
\# : docker context ls
| NAME | DESCRIPTION | DOCKER ENDPOINT | ERROR |
| ------ | ------ | ------ | ------ |
| default | Current DOCKER_HOST based configuration | unix:///Users/dhanush/.docker/run/docker.sock | |
| desktop-linux | Docker Desktop | unix:///Users/dhanush/.docker/run/docker.sock | |

**Comment by r4victor** [comment]
@dhanush-2501, please provide the output of `docker version`.

I suspect the problem is that you're missing ` /var/run/docker.sock`. It [was removed in Docker Desktop 4.13.0](https://docs.docker.com/desktop/release-notes/#docker-desktop-4130) and [added back in 4.13.1](https://docs.docker.com/desktop/release-notes/#4131). Try updating Docker Desktop and see if it helps.

**Comment by dhanush-2501** [comment]
@r4victor yeah resolved by creating a sym link 
`ln -s /Users/username/.docker/run/docker.sock /var/run/docker.sock`

**Comment by dhanush-2501** [comment]
> @dhanush-2501, please provide the output of `docker version`.
> 
> I suspect the problem is that you're missing ` /var/run/docker.sock`. It [was removed in Docker Desktop 4.13.0](https://docs.docker.com/desktop/release-notes/#docker-desktop-4130) and [added back in 4.13.1](https://docs.docker.com/desktop/release-notes/#4131). Try updating Docker Desktop and see if it helps.

docker version `4.21.1`
