### ISSUE TITLE
[Bug]: ERROR Can't establish SSH tunnel with the container

### ISSUE THREAD

**Issue by dhanush-2501** [dstackai/dstack#561]
### dstack version

0.10.4

### Python version

3.10.9

### Host OS

macOS 13.4.1

### Host Arch

ARM

### What happened?

While executing dstack examples locally, `dstack run fastapi-app --reload` command resulted in 
```
ERROR Can't establish SSH tunnel with the container
Aborting...
Aborted 
```
### Relevant log output

```shell
dstack will execute the following plan:

 CONFIGURATION            USER   PROJECT  INSTANCE  RESOURCES       SPOT POLICY  BUILD 
 fastapi-app/.dstack.yml  admin  local    -         4xCPUs, 3933MB  auto         No    

Continue? [y/n]: y

Provisioning...

 RUN             USER   INSTANCE  SPOT  STATUS     SUBMITTED 
 fast-penguin-1  admin  -         no    Submitted  now       

Starting SSH tunnel...

To stop, press Ctrl+C.

INFO:     Will watch for changes in these directories: ['/workflow/fastapi-app']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [1] using StatReload
INFO:     Started server process [54]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR Can't establish SSH tunnel with the container
Aborting...
Aborted
```

#### steps to reproduce 
- `dstack start`
- `cd dstack-examples`
- `dstack init`
- `dstack run fastapi-app --reload`

**Comment by Egor-S** [comment]
@dhanush-2501 can you reproduce it using the latest release 0.10.5?

**Comment by dhanush-2501** [comment]
@Egor-S Let me try and update you

**Comment by dhanush-2501** [comment]
@Egor-S Nope, it didn't work. Got an new error.
`dstack init` and `dstack run fastapi-app --reload` both resulted in the same output below
```shell
Provisioning is taking longer than usual, possibly because of having too many or large local files that haven’t been pushed to Git. Tip: Exclude unnecessary files from provisioning by using the `.gitignore` file.

Traceback (most recent call last):
  File "/Users/dhanush/Documents/dstack-examples/myenv/bin/dstack", line 8, in <module>
    sys.exit(main())
  File "/Users/dhanush/Documents/dstack-examples/myenv/lib/python3.10/site-packages/dstack/_internal/cli/main.py", line 51, in main
    check_cli_errors(args.func)(args)
  File "/Users/dhanush/Documents/dstack-examples/myenv/lib/python3.10/site-packages/dstack/_internal/cli/common.py", line 143, in decorator
    func(*args, **kwargs)
  File "/Users/dhanush/Documents/dstack-examples/myenv/lib/python3.10/site-packages/dstack/_internal/cli/common.py", line 143, in decorator
    func(*args, **kwargs)
  File "/Users/dhanush/Documents/dstack-examples/myenv/lib/python3.10/site-packages/dstack/_internal/cli/commands/__init__.py", line 44, in __command
    self._command(args)
  File "/Users/dhanush/Documents/dstack-examples/myenv/lib/python3.10/site-packages/dstack/_internal/cli/common.py", line 129, in decorator
    func(*args, **kwargs)
  File "/Users/dhanush/Documents/dstack-examples/myenv/lib/python3.10/site-packages/dstack/_internal/cli/commands/run/__init__.py", line 142, in _command
    run_plan = hub_client.get_run_plan(configurator)
  File "/Users/dhanush/Documents/dstack-examples/myenv/lib/python3.10/site-packages/dstack/api/hub/_client.py", line 269, in get_run_plan
    run_plan = self._api_client.get_run_plan(jobs)
  File "/Users/dhanush/Documents/dstack-examples/myenv/lib/python3.10/site-packages/dstack/api/hub/_api_client.py", line 89, in get_run_plan
    resp.raise_for_status()
  File "/Users/dhanush/Documents/dstack-examples/myenv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: http://127.0.0.1:3000/api/project/local/runs/get_plan
```

**Comment by Egor-S** [comment]
@dhanush-2501 have you restarted the hub server too after the upgrade? I ran `dstack run fastapi-app --reload` with the latest release and the hub server without any problems

**Comment by dhanush-2501** [comment]
tried it. didn't worked🥲

**Comment by Egor-S** [comment]
@dhanush-2501 I need more details to resolve your case. What exactly did not work? Are we solving the original SSH tunnel problem or 422 from the server?

I noticed a warning about the large size of the diff — let's run an experiment in a clean environment.

1. Delete ~/.dstack/local_backend/local (or just rename it)
2. Run `dstack --version && dstack start`. Output must be 0.10.5
3. Get a fresh clone of dstack examples and cd into
4. Run `dstack --version && dstack init && dstack run fastapi-app --reload`. Again, the output must be 0.10.5

Please, follow these steps and provide output here.

**Comment by dhanush-2501** [comment]
Right now we are solving the 422 from the server, the original SSH tunnel problem didn't arrive in the latest version

**Comment by dhanush-2501** [comment]
now I am repeatedly getting 
```
Provisioning is taking longer than usual, possibly because of having too many or large local files that haven’t been pushed to Git. Tip: Exclude unnecessary files from provisioning by using the .gitignore file.
```
Even tried completely reinstalling dstack

**Comment by Egor-S** [comment]
@dhanush-2501 this warning should not appear on a freshly cloned repository. Have you completed the third step?

> Get a fresh clone of dstack examples and cd into

i.e. `git clone https://github.com/dstackai/dstack-examples.git && cd dstack-examples`

**Comment by dhanush-2501** [comment]
@Egor-S yes i did.

**Comment by dhanush-2501** [comment]
Let me try with a freshly installed dstack one more time and will update you

**Comment by dhanush-2501** [comment]
@Egor-S It's working now. Issue resolved

**Comment by Egor-S** [comment]
@dhanush-2501, great. Thank you for reporting
