### ISSUE TITLE
[Bug]: AWS Bucket Project Element Value validation error

### ISSUE THREAD

**Issue by dhanush-2501** [dstackai/dstack#567]
### dstack version

0.10.4

### Python version

3.10.9

### Host OS

macOS 13.4.1

### Host Arch

ARM

### What happened?

While setting up the project in the dstack hub, after entering AWS credentials no regions and buckets got listed.
`dstack start` command resulted in 
`validation error for AWSBucketProjectElementValue
region
 none is not an allowed value (type=type_error.none.not_allowed)`
No error message is shown on the hub

### Relevant log output

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/dhanush/Library/Python/3.10/lib/python/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/Users/dhanush/Library/Python/3.10/lib/python/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "/Users/dhanush/Library/Python/3.10/lib/python/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/homebrew/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/opt/homebrew/lib/python3.10/site-packages/dstack/_internal/hub/main.py", line 77, in app_logging
    response = await call_next(request)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/homebrew/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/homebrew/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/opt/homebrew/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/opt/homebrew/lib/python3.10/site-packages/dstack/_internal/hub/routers/projects.py", line 36, in get_backend_config_values
    result = await run_async(configurator.configure_project, config.__root__)
  File "/opt/homebrew/lib/python3.10/site-packages/dstack/_internal/hub/utils/common.py", line 5, in run_async
    return await asyncio.get_running_loop().run_in_executor(None, func, *args)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/dstack/_internal/hub/services/backends/aws/configurator.py", line 82, in configure_project
    project_values.s3_bucket_name = self._get_hub_buckets_element(
  File "/opt/homebrew/lib/python3.10/site-packages/dstack/_internal/hub/services/backends/aws/configurator.py", line 184, in _get_hub_buckets_element
    AWSBucketProjectElementValue(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AWSBucketProjectElementValue
region
  none is not an allowed value (type=type_error.none.not_allowed)
```

### Additional Information

<img width="1435" alt="dstack_s3_bucket_accces_denied" src="https://github.com/dstackai/dstack/assets/79148926/91f8297c-3a10-4047-84f2-4c9927834755">

# Steps to reproduce
- `dstack start`
- head over to the dstack hub and click add
- choose AWS as backend type
- enter access ID
- enter Secret access key
- check the `dstack start` command terminal output

**Comment by r4victor** [comment]
@dhanush-2501, this should be fixed in 0.10.5. Try updating dstack and see if it helps.

**Comment by dhanush-2501** [comment]
@r4victor  still I am getting the same error though I have been using 0.10.5

**Comment by r4victor** [comment]
I was able to reproduce the issue with 0.10.4 but not with 0.10.5. We sometimes see version-related problems when the CLI is using the latest version but the server is not. So ensure the server is 0.10.5. If the problem persists, I may suggest you installing from master, debug the problem, and open a PR to fix it. We'd greatly appreciate it!

**Comment by dhanush-2501** [comment]
@r4victor Hey buddy, actually the server is also running at 0.10.5 , executed `dstack --version && dstack start`below is the result. so hope that clears your doubt.
```
0.10.5
The server is available at http://127.0.0.1:3000?token=34a85b1c-3c7a-449f-8dc0-8dbf3df23dd6
```

**Comment by dhanush-2501** [comment]
Yeah sure, let me try with the master copy and will update you.

**Comment by dhanush-2501** [comment]
@r4victor I followed the Readme under the hub directory and after installing when I run `npm run start` the hub is getting opened and it  displays "Invalid token
For getting the authorization token, contact to the administrator"
 asking for an authorization token and below is what I get in the terminal.
```shell
<e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:3000/api/users/info to http://127.0.0.1:3001/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
Am I following the correct procedure?

**Comment by r4victor** [comment]
You're on the right track. If you don't need to develop the frontend but only the API, you can build the frontend. When running the webpack dev server (as you do), you should run the API on port 3001: `dstack start --port 3001`. The readme was unclear. I updated it.

**Comment by dhanush-2501** [comment]
Hey thanks for updating the readme actually was about to request that, glad you did it by yourself.

**Comment by dhanush-2501** [comment]
Hey @r4victor ,

I followed the steps you provided to run the code from the source, but when I click on AWS, I encounter an error saying "Unsupported backend type. Dependencies for AWS backend are not installed. Run pip install dstack[aws] to enable AWS support."

Since I am running the code from the source, do I still need to execute `pip install dstack[aws]`?
In my opinion, I would say that the contributing guide is still unclear, It doesn't clearly specify how to run from the source.

Looking forward to your guidance.

Thanks!

**Comment by r4victor** [comment]
You'd do `pip install -e '.[aws]'`. I've just update the contributing guide so that it installs all the dependencies.

**Comment by dhanush-2501** [comment]
thx, Let me try

**Comment by r4victor** [comment]
I was able to debug the issue. It was indeed a problem with dstack that didn't occur when having aws default creds on the machine (by accident). Fixed now. Please check if it works and thanks for the patience.
