### ISSUE TITLE
[Bug]: A run fails on Azure if re-submitted with the same name using a different region

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#695]
### dstack version

Any

### Host OS

Any

### Host Arch

Any

### What happened?

Submit a run with the same name several times in Azure using multiple regions.
At certain point, you'll start receive the following error:

```
Traceback (most recent call last):
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/hub/main.py", line 91, in app_logging
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/hub/routers/runners.py", line 56, in run
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/hub/routers/util.py", line 74, in call_backend
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/hub/utils/common.py", line 11, in run_async
  File "/Users/cheptsov/miniforge3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/backend/base/__init__.py", line 308, in run_job
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/backend/base/jobs.py", line 130, in run_job
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/backend/base/jobs.py", line 123, in run_job
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/backend/base/jobs.py", line 212, in _try_run_job
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/backend/azure/compute.py", line 131, in run_instance
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/backend/azure/compute.py", line 302, in _run_instance
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/backend/azure/compute.py", line 477, in _launch_instance
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/backend/azure/compute.py", line 398, in _launch_instance
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 76, in wrapper_use_tracer
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/azure/mgmt/compute/v2023_03_01/operations/_operations.py", line 15648, in begin_create_or_update
    raw_result = self._create_or_update_initial(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/azure/mgmt/compute/v2023_03_01/operations/_operations.py", line 15518, in _create_or_update_initial
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/azure/core/exceptions.py", line 109, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: (InvalidResourceLocation) The resource 'dstack-streamlit-demo' already exists in location 'westeurope' in resource group 'NetworkWatcherRG'. A resource with the same name cannot be created in location 'eastus'. Please select a new resource name.
Code: InvalidResourceLocation
Message: The resource 'dstack-streamlit-demo' already exists in location 'westeurope' in resource group 'NetworkWatcherRG'. A resource with the same name cannot be created in location 'eastus'. Please select a new resource name.
```

**Comment by peterschmidt85** [comment]
All old resources should be deleted when I delete the run via `hub_client.delete_run`

**Comment by peterschmidt85** [comment]
A better alternative perhaps to this would be to use the region as a suffix in the name of the resource.

**Comment by peterschmidt85** [comment]
This issue is stale because it has been open for 30 days with no activity.
