### ISSUE TITLE
[Bug]: A run fails with an exception in GCP

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#696]
### dstack version

Any

### Host OS

Any

### Host Arch

Any

### What happened?

```
dstack run . -f text-generation-inference/.dstack.yml --gpu 40GB --spot-auto --backend gcp --force-build
```

```
Traceback (most recent call last):
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/hub/main.py", line 91, in app_logging
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/hub/routers/runners.py", line 56, in run
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/hub/routers/util.py", line 74, in call_backend
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/hub/utils/common.py", line 11, in run_async
  File "/Users/cheptsov/miniforge3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/backend/base/__init__.py", line 308, in run_job
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/backend/base/jobs.py", line 130, in run_job
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/backend/base/jobs.py", line 123, in run_job
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/backend/base/jobs.py", line 212, in _try_run_job
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/backend/gcp/compute.py", line 166, in run_instance
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/backend/gcp/compute.py", line 627, in _run_instance
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/backend/gcp/compute.py", line 712, in _launch_instance
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/dstack/_internal/backend/gcp/compute.py", line 896, in _create_instance
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/google/cloud/compute_v1/services/instances/client.py", line 3214, in insert
    response = rpc(
               ^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/google/api_core/grpc_helpers.py", line 72, in error_remapped_callable
    return callable_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/google/cloud/compute_v1/services/instances/transports/rest.py", line 3163, in __call__
    raise core_exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://compute.googleapis.com/compute/v1/projects/dstack/zones/europe-west4-c/instances: Invalid value for field 'resource.machineType': 'zones/europe-west4-c/machineTypes/a2-highgpu-1g'. Machine type with name 'a2-highgpu-1g' does not exist in zone 'europe-west4-c'.
```

**Comment by Egor-S** [comment]
Now we iterate over all zones in a region, however, some instances are not available in each zone of the region.

Possible solutions:
1. Handle BadRequest error containing `does not exist in zone`
2. Lookup zone availability in the catalog before launching an instance
