### ISSUE TITLE
Service provisioning fails with "Certbot failed" error

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#705]
1. Create a gateway in GCP
2. Create A record for "*.my-subdomain.dstack.ai" pointing to gateway IP.
3. Run a service in GCP

Server logs:

```
DEBUG 2023-10-11T16:00:05.874 dstack._internal.server.main Processed request POST http://127.0.0.1:8000/api/project/main/repos/get in 0.005131s
DEBUG 2023-10-11T16:00:23.278 dstack._internal.server.main Processed request POST http://127.0.0.1:8000/api/project/main/gateways/create in 17.400756s
DEBUG 2023-10-11T16:00:23.388 dstack._internal.server.main Processed request POST http://127.0.0.1:8000/api/project/main/gateways/set_wildcard_domain in 0.105004s
DEBUG 2023-10-11T16:00:23.395 dstack._internal.server.main Processed request POST http://127.0.0.1:8000/api/project/main/gateways/get in 0.004635s
DEBUG 2023-10-11T16:01:08.956 dstack._internal.server.main Processed request POST http://127.0.0.1:8000/api/project/main/repos/get in 0.004904s
DEBUG 2023-10-11T16:01:12.436 dstack._internal.server.main Processed request POST http://127.0.0.1:8000/api/project/main/runs/get_plan in 3.474289s
DEBUG 2023-10-11T16:01:13.350 dstack._internal.server.main Processed request POST http://127.0.0.1:8000/api/project/main/repos/upload_code?repo_id=my_dstack_public-oqy6glxo in 0.030997s
DEBUG 2023-10-11T16:01:13.397 dstack._internal.server.services.gateways Configuring ubuntu@35.196.122.6 gateway over SSH: [{'hostname': 'wicked-hound-1-0.victor-dev.dstack.ai', 'port': 443, 'secure': True}]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/main.py", line 86, in log_request
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/routers/runs.py", line 86, in submit_run
    return await runs.submit_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/services/runs.py", line 157, in submit_run
    await gateways.register_service_jobs(session, project, jobs)
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/services/gateways.py", line 233, in register_service_jobs
    await run_async(
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/utils/common.py", line 5, in run_async
    return await asyncio.get_running_loop().run_in_executor(None, func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/.pyenv/versions/3.11.2/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/services/gateways.py", line 293, in configure_gateway_over_ssh
    raise ConfigurationError("Certbot failed, check wildcard domain correctness")
dstack._internal.core.errors.ConfigurationError: Certbot failed, check wildcard domain correctness
```

**Comment by Egor-S** [comment]
The wildcard domain seems to be misconfigured — dnslookup can't resolve it.

If you use a hosted zone in Route 53, add an NS record from the top-level domain to redirect DNS queries to the hosted zone.
