### ISSUE TITLE
Service provisioning fails with `FileNotFoundError: [Errno 2] No such file or directory: 'certbot'`

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#706]
1. Create gateway `dstack gateway create --backend gcp --domain 'victor-dev.dstack.ai' --region us-east1`
2. Run service: `dstack run . -f .dstack/confs/service.yaml --backend gcp`.

Note: I didn't add DNS records to point the domain to the gateway.

CLI logs:

```
✗ dstack gateway create --backend gcp --domain 'victor-dev.dstack.ai' --region us-east1 
 BACKEND  REGION      NAME        ADDRESS         DOMAIN             DEFAULT 
 gcp      us-east1-b  dull-sheep  35.190.185.109  victor-dev.dstac…  ✓       

(venv) ➜  my_dstack_public git:(master) ✗ dstack run . -f .dstack/confs/service.yaml --backend gcp
 Configuration  .dstack/confs/service.yaml 
 Project        main                       
 User           admin                      
 Min resources  2xCPUs, 8GB                
 Max price      -                          
 Max duration   -                          
 Spot policy    auto                       
 Retry policy   no                         

 #  BACKEND  REGION    INSTANCE       RESOURCES     SPOT  PRICE       
 1  gcp      us-east1  e2-standard-2  2xCPUs, 8GB   yes   $0.020103   
 2  gcp      us-east1  e2-highmem-2   2xCPUs, 16GB  yes   $0.02712    
 3  gcp      us-east1  e2-standard-4  4xCPUs, 16GB  yes   $0.040207   
    ...                                                               

Continue? [y/n]: y
Unexpected dstack server error
```

Server logs:

```
DEBUG 2023-10-13T08:51:28.284 dstack._internal.server.main Processed request POST http://127.0.0.1:8000/api/project/main/repos/get in 0.005509s
DEBUG 2023-10-13T08:51:43.313 dstack._internal.server.main Processed request POST http://127.0.0.1:8000/api/project/main/gateways/create in 15.025545s
DEBUG 2023-10-13T08:51:43.338 dstack._internal.server.main Processed request POST http://127.0.0.1:8000/api/project/main/gateways/set_wildcard_domain in 0.019990s
DEBUG 2023-10-13T08:51:43.349 dstack._internal.server.main Processed request POST http://127.0.0.1:8000/api/project/main/gateways/get in 0.008370s
DEBUG 2023-10-13T08:52:08.453 dstack._internal.server.main Processed request POST http://127.0.0.1:8000/api/project/main/repos/get in 0.006666s
DEBUG 2023-10-13T08:52:12.142 dstack._internal.server.main Processed request POST http://127.0.0.1:8000/api/project/main/runs/get_plan in 3.683545s
DEBUG 2023-10-13T08:52:12.933 dstack._internal.server.main Processed request POST http://127.0.0.1:8000/api/project/main/repos/upload_code?repo_id=my_dstack_public-oqy6glxo in 0.029476s
DEBUG 2023-10-13T08:52:13.055 dstack._internal.server.services.gateways Configuring ubuntu@35.190.185.109 gateway over SSH: [{'hostname': 'mighty-donkey-1-0.victor-dev.dstack.ai', 'port': 443, 'secure': True}]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/main.py", line 86, in log_request
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venv/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/routers/runs.py", line 86, in submit_run
    return await runs.submit_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/services/runs.py", line 157, in submit_run
    await gateways.register_service_jobs(session, project, jobs)
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/services/gateways.py", line 238, in register_service_jobs
    await run_async(
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/utils/common.py", line 5, in run_async
    return await asyncio.get_running_loop().run_in_executor(None, func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/.pyenv/versions/3.11.2/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/services/gateways.py", line 298, in configure_gateway_over_ssh
    raise SSHError(stderr.decode())
dstack._internal.core.errors.SSHError: Warning: Permanently added '35.190.185.109' (ED25519) to the list of known hosts.
Traceback (most recent call last):
  File "<stdin>", line 177, in <module>
  File "<stdin>", line 52, in main
  File "<stdin>", line 170, in run_certbot
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'certbot'
```

**Comment by r4victor** [comment]
After I waited for a while, I got the appropriate error message:

```
✗ dstack run . -f .dstack/confs/service.yaml --backend gcp
 Configuration  .dstack/confs/service.yaml 
 Project        main                       
 User           admin                      
 Min resources  2xCPUs, 8GB                
 Max price      -                          
 Max duration   -                          
 Spot policy    auto                       
 Retry policy   no                         

 #  BACKEND  REGION    INSTANCE       RESOURCES     SPOT  PRICE       
 1  gcp      us-east1  e2-standard-2  2xCPUs, 8GB   yes   $0.020103   
 2  gcp      us-east1  e2-highmem-2   2xCPUs, 16GB  yes   $0.02712    
 3  gcp      us-east1  e2-standard-4  4xCPUs, 16GB  yes   $0.040207   
    ...                                                               

Continue? [y/n]: y
Certbot failed, ensure the domain is valid
```

I believe the problem was that certbot had too little time to install.
