### ISSUE TITLE
ML model after ds.pull() doesn't work 

### ISSUE THREAD

**Issue by aniketwattamwar** [dstackai/dstack#74]
Traceback (most recent call last):
  File "d:\ML_projects\dstack_proj\loan_prediction.py", line 56, in <module>
    model = ds.pull('/dstack/Random_Forest')
  File "d:\ML_projects\dstack_proj\env_dstack\lib\site-packages\dstack\_init_.py", line 232, in pull
    return _pull(create_context(stack, profile), params, decoder, **kwargs)
  File "d:\ML_projects\dstack_proj\env_dstack\lib\site-packages\dstack\_init_.py", line 241, in _pull
    return decoder.decode(pull_data(context, params, **kwargs))
  File "d:\ML_projects\dstack_proj\env_dstack\lib\site-packages\dstack\auto.py", line 76, in decode
    return self.find_handler(data.media_type(), self.decoders).decode(data)
  File "d:\ML_projects\dstack_proj\env_dstack\lib\site-packages\dstack\sklearn\handlers.py", line 49, in decode
    return persist.decode(data.data.stream())
  File "d:\ML_projects\dstack_proj\env_dstack\lib\site-packages\dstack\sklearn\persistence.py", line 35, in decode
    return joblib.load(stream)
  File "d:\ML_projects\dstack_proj\env_dstack\lib\site-packages\joblib\numpy_pickle.py", line 574, in load
    with _read_fileobject(fobj, filename, mmap_mode) as fobj:
  File "c:\program files\python36\Lib\contextlib.py", line 81, in _enter_
    return next(self.gen)
  File "d:\ML_projects\dstack_proj\env_dstack\lib\site-packages\joblib\numpy_pickle_utils.py", line 124, in _read_fileobject
    compressor = _detect_compressor(fileobj)
  File "d:\ML_projects\dstack_proj\env_dstack\lib\site-packages\joblib\numpy_pickle_utils.py", line 73, in _detect_compressor
    fileobj.seek(0)
io.UnsupportedOperation: seek

**Comment by peterschmidt85** [comment]
@aniketwattamwar Could you please share the steps to reproduce? The exact code sample (both push and pull), and the info on the Python environment.

**Comment by aniketwattamwar** [comment]
@peterschmidt85 
Here is the code:
https://github.com/aniketwattamwar/dstack_proj

**Comment by peterschmidt85** [comment]
@aniketwattamwar Could you please test this version to see if it fixes the problem:
`pip install --index-url https://test.pypi.org/simple/ --upgrade --no-cache-dir --extra-index-url=https://pypi.org/simple/ dstack==0.6dev24`

**Comment by aniketwattamwar** [comment]
Hi @peterschmidt85 the new version solved my problem
Thank you
