### ISSUE TITLE
Treat a Git repo without a tracking remote branch as a local repo but show a warning

### ISSUE THREAD

**Issue by kengz** [dstackai/dstack#822]
### dstack version

0.13.0

### Python version

3.11.0

### Host OS

MacOS 13.1

### Host Arch

ARM

### What happened?

Full repro instruction to obtain error "The repo is not initialized..."

```bash
mkdir test
cd test/

pip install 'dstack[all]' -U
dstack --version
# 0.13.0

echo 'type: dev-environment                                                                         
python: "3.11"
ide: vscode
' > .dstack.yml

# cleanup ~/.dstack
rm -rf ~/.dstack
# in a separate shell, run:
dstack server
# in another shell, run:
dstack run . -f .dstack.yml
# The repo is not initialized. Run `dstack init` to initialize the repo.
```

**Comment by peterschmidt85** [comment]
Works after `dstack init`.
But for a git repo - a new branch still needs to be pushed to remote for it to work. 

```
➜ dstack run . -f .dstack/train.dstack.yml
Traceback (most recent call last):
  File "/Users/keng/projects/lean-dl-example/.venv/bin/dstack", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/keng/projects/lean-dl-example/.venv/lib/python3.11/site-packages/dstack/_internal/cli/main.py", line 64, in main
    args.func(args)
  File "/Users/keng/projects/lean-dl-example/.venv/lib/python3.11/site-packages/dstack/_internal/cli/commands/run.py", line 94, in _command
    repo = self.api.repos.load(Path.cwd())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keng/projects/lean-dl-example/.venv/lib/python3.11/site-packages/dstack/api/_public/repos.py", line 114, in load
    repo = load_repo(repo_config)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keng/projects/lean-dl-example/.venv/lib/python3.11/site-packages/dstack/_internal/core/services/repos.py", line 134, in load_repo
    return RemoteRepo(repo_id=config.repo_id, local_repo_dir=config.path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keng/projects/lean-dl-example/.venv/lib/python3.11/site-packages/dstack/_internal/core/models/repos/remote.py", line 99, in __init__
    raise RepoError("No remote branch is configured")
dstack._internal.core.models.repos.remote.RepoError: No remote branch is configured
```

**Comment by peterschmidt85** [comment]
Suggestion:
If it's a Git repo but there is no tracking remote branch, show a warning but treat it as a local repo.

**Comment by peterschmidt85** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by peterschmidt85** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.

**Comment by r4victor** [comment]
Closing as local repos are to be deprecated #2974
