### ISSUE TITLE
[Bug]: Server raises SSHError when starting a service if fails to connect to gateway

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#848]
### dstack version

master

### Python version

3.11

### Host OS

macOS 13.4

### Host Arch

ARM

### What happened?

I created a dstack cloud gateway without specifying DNS records for it. When running a service, I got `Unexpected dstack server error`. The server crashed with `SSHError`. The server should handle the case when the gateway is not available.

### Server logs

```shell
The dstack server (no version) is running at http://localhost:8000
The admin token is .
DEBUG 2024-01-25T14:17:39.678 dstack._internal.server.app Processed request POST http://localhost:8000/api/project/r4victor-local/repos/get in 0.006730s
DEBUG 2024-01-25T14:17:50.869 dstack._internal.server.app Processed request POST http://localhost:8000/api/project/r4victor-local/runs/get_plan in 11.183901s
DEBUG 2024-01-25T14:18:02.900 dstack._internal.server.app Processed request POST http://localhost:8000/api/project/r4victor-local/runs/get in 0.019240s
DEBUG 2024-01-25T14:18:02.934 dstack._internal.server.app Processed request POST http://localhost:8000/api/project/r4victor-local/repos/upload_code?repo_id=my_dstack_public-oqy6glxo in 0.025395s
DEBUG 2024-01-25T14:18:02.944 dstack._internal.server.services.gateways Running service preflight: tasty-mole-1.r4victor-local.victor-dev.dstack.ai
DEBUG 2024-01-25T14:18:06.122 dstack._internal.core.services.ssh.tunnel SSH tunnel failed: b'Connection timed out during banner exchange\r\nConnection to 3.250.197.206 port 22 timed out\r\n'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/fastapi/applications.py", line 1115, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/app.py", line 174, in check_client_version
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/app.py", line 154, in log_request
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/venvx/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/routers/runs.py", line 84, in submit_run
    return await runs.submit_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/services/runs.py", line 189, in submit_run
    await gateways.register_service_jobs(session, project, run_spec.run_name, jobs)
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/services/gateways/__init__.py", line 273, in register_service_jobs
    await run_async(
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/utils/common.py", line 13, in run_async
    return await asyncio.get_running_loop().run_in_executor(None, func_with_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/.pyenv/versions/3.11.2/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/services/gateways/__init__.py", line 292, in _gateway_preflight
    with gateway_tunnel_client(domain, gateway_ssh_private_key) as client:
  File "/Users/r4victor/.pyenv/versions/3.11.2/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/server/services/gateways/ssh.py", line 11, in gateway_tunnel_client
    with RunnerTunnel(
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/core/services/ssh/tunnel.py", line 51, in __enter__
    self.open()
  File "/Users/r4victor/Projects/dstack/dstack/src/dstack/_internal/core/services/ssh/tunnel.py", line 44, in open
    raise get_ssh_error(r.stderr)
dstack._internal.core.errors.SSHError: Connection timed out during banner exchange
Connection to 3.250.197.206 port 22 timed out
```

**Comment by peterschmidt85** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by peterschmidt85** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
