### ISSUE TITLE
Allow to use a bucket from another region but show a warning

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#93]
Currently, the runner doesn't work

```
JZyJ7EqY=, api error PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x16d4bca]

goroutine 1 [running]:
gitlab.com/dstackai/dstackai-runner/internal/executor.(*Executor).Shutdown.func1()
        /go/src/gitlab.com/dstackai/dstackai-runner/internal/executor/executor.go:363 +0xc5
panic({0x1b17880, 0x2932160})
        /usr/local/go/src/runtime/panic.go:838 +0x207
gitlab.com/dstackai/dstackai-runner/internal/backend/s3.S3.Shutdown({{0xc0000533e0, 0x9}, {0xc0000533c0, 0x9}, {0xc0000a2ac0, 0x20}, 0x0, {0x0, 0x0, 0x0}, ...}, ...)
        /go/src/gitlab.com/dstackai/dstackai-runner/internal/backend/s3/backend.go:170 +0x4a
gitlab.com/dstackai/dstackai-runner/internal/executor.(*Executor).Shutdown(0x203000?, {0x2068f70, 0xc00012e000})
        /go/src/gitlab.com/dstackai/dstackai-runner/internal/executor/executor.go:366 +0x7a
panic({0x1be4d80, 0xc0006021b0})
        /usr/local/go/src/runtime/panic.go:838 +0x207
gitlab.com/dstackai/dstackai-runner/internal/executor.(*Executor).Init.func1()
        /go/src/gitlab.com/dstackai/dstackai-runner/internal/executor/executor.go:48 +0xcb
panic({0x1be4d80, 0xc0006021b0})
        /usr/local/go/src/runtime/panic.go:838 +0x207
gitlab.com/dstackai/dstackai-runner/internal/executor.(*Executor).Init(0xc00017be30, {0x20699f0, 0xc0004a8c80}, {0x1cdebfd, 0x6})
        /go/src/gitlab.com/dstackai/dstackai-runner/internal/executor/executor.go:59 +0xd1e
main.start(0x599bae?, {0x1cdebfd, 0x6})
        /go/src/gitlab.com/dstackai/dstackai-runner/main.go:56 +0x506
main.App.func2(0xc00004f6e0?)
        /go/src/gitlab.com/dstackai/dstackai-runner/cmd.go:67 +0x55
github.com/urfave/cli/v2.(*Command).Run(0xc000018120, 0xc00007fe80)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5bb
github.com/urfave/cli/v2.(*App).RunContext(0xc0002bc820, {0x2068f70?, 0xc00012e000}, {0xc00012c000, 0x2, 0x2})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb48
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.App()
        /go/src/gitlab.com/dstackai/dstackai-runner/cmd.go:74 +0x64d
main.main()
        /go/src/gitlab.com/dstackai/dstackai-runner/main.go:25 +0x17
```

**Comment by peterschmidt85** [comment]
With 0.0.9, dstack config will not allow to configure an S3 bucket from a different region. 
You can already try it now if you install 0.0.9rc2 via `pip install dstack -U --pre`
