### ISSUE TITLE
[Bug]: Exceptions in the catalog.query aren't handled in the dstack

### ISSUE THREAD

**Issue by TheBits** [dstackai/dstack#979]
### dstack version

0.16.2

### Python version

3.11.8

### Host OS

Arch Linux

### Host Arch

x86_64

### What happened?

I've installed `dstack=0.16.2` with cudo support and `gpuhunt=0.0.4` without it.

When I run the `dstack run . -f task.dstack.yaml -b cudo  --gpu 4`, I get an unhandled error in the server. No offers at all, and no explanation in the CLI.

### CLI logs

```shell
❯ dstack run . -f task.dstack.yaml -b cudo  --gpu 4
 Configuration          task.dstack.yaml
 Project                main
 User                   admin
 Pool name              default-pool
 Min resources          2..xCPU, 8GB.., 4xGPU
 Max price              -
 Max duration           72h
 Spot policy            auto
 Retry policy           no
 Creation policy        reuse-or-create
 Termination policy     destroy-after-idle
 Termination idle time  300s

Continue? [y/n]: n

Exiting...
```
```


### Server logs

```shell
DEBUG 2024-03-08T12:01:18.432 dstack._internal.server.app Processed request POST http://127.0.0.1:3000/api/project/main/runs/get_plan in 3.616101s
DEBUG 2024-03-08T12:01:37.044 dstack._internal.server.app Processed request POST http://127.0.0.1:3000/api/project/main/repos/get in 0.010334s
ERROR 2024-03-08T12:01:37.064 dstack._internal.server.services.backends Got exception when requesting offers from backend BackendType.CUDO
Traceback (most recent call last):
  File "/home/thebits/dstack/dstack/.direnv/python-3.11/lib/python3.11/site-packages/dstack/_internal/server/utils/common.py", line 13, in run_async
    return await asyncio.get_running_loop().run_in_executor(None, func_with_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thebits/dstack/dstack/.direnv/python-3.11/lib/python3.11/site-packages/dstack/_internal/core/backends/cudo/compute.py", line 37, in get_offers
    offers = get_catalog_offers(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/thebits/dstack/dstack/.direnv/python-3.11/lib/python3.11/site-packages/dstack/_internal/core/backends/base/offers.py", line 32, in get_catalog_offers
    for item in catalog.query(**asdict(q)):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thebits/dstack/dstack/.direnv/python-3.11/lib/python3.11/site-packages/gpuhunt/_internal/catalog.py", line 119, in query
    raise ValueError(f"Unknown provider: {p}")
ValueError: Unknown provider: cudo
```
```


### Runner logs

_No response_

### Additional Information

_No response_

**Comment by r4victor** [comment]
The error is handled but since the error is unexpected it is logged with stacktrace. It's expected that no offers shown since gpuhunt does not return any. Not a bug.
