### ISSUE TITLE
[Bug]: Errors in the gpuhunt.default_catalog aren't handled

### ISSUE THREAD

**Issue by TheBits** [dstackai/dstack#980]
### dstack version

0.16.2

### Python version

3.11.8

### Host OS

Arch Linux

### Host Arch

x86_64

### What happened?

This bug is similar to #978.

I started the command `dstack run . -f task.dstack.yaml -b cudo --gpu 4` when I had a network error. Then the dstack server shows an unhandled exception with stack trace.

### Server logs

```shell
2024-03-06T11:00:56.482 dstack._internal.server.app Processed request POST http://127.0.0.1:3000/api/project/main/repos/get in 0.012022s
ERROR 2024-03-06T11:00:57.529 dstack._internal.server.services.backends Got exception when requesting offers from backend BackendType.CUDO
Traceback (most recent call last):
  File "/usr/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.11/http/client.py", line 1298, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1344, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1293, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1052, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 990, in send
    self.connect()
  File "/usr/lib/python3.11/http/client.py", line 1463, in connect
    super().connect()
  File "/usr/lib/python3.11/http/client.py", line 956, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thebits/dstack/dstack/.direnv/python-3.11/lib/python3.11/site-packages/dstack/_internal/server/utils/common.py", line 13, in run_async
    return await asyncio.get_running_loop().run_in_executor(None, func_with_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thebits/dstack/dstack/.direnv/python-3.11/lib/python3.11/site-packages/dstack/_internal/core/backends/cudo/compute.py", line 31, in get_offers
    offers = get_catalog_offers(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/thebits/dstack/dstack/.direnv/python-3.11/lib/python3.11/site-packages/dstack/_internal/core/backends/base/offers.py", line 31, in get_catalog_offers
    catalog = catalog if catalog is not None else gpuhunt.default_catalog()
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thebits/dstack/dstack/.direnv/python-3.11/lib/python3.11/site-packages/gpuhunt/_internal/default.py", line 20, in default_catalog
    catalog.load()
  File "/home/thebits/dstack/dstack/.direnv/python-3.11/lib/python3.11/site-packages/gpuhunt/_internal/catalog.py", line 163, in load
    version = self.get_latest_version()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thebits/dstack/dstack/.direnv/python-3.11/lib/python3.11/site-packages/gpuhunt/_internal/catalog.py", line 174, in get_latest_version
    with urllib.request.urlopen(version_url) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 113] No route to host>
DEBUG 2024-03-06T11:00:57.549 dstack._internal.server.app Processed request POST http://127.0.0.1:3000/api/project/main/runs/get_plan in 1.058397s
```

**Comment by r4victor** [comment]
You can see from the second line that the error is handled but since the error is unexpected it is logged with stacktrace. So I wouldn't consider it a bug.
