### ISSUE TITLE
[Bug]: An ugly error occurs when I misspell the provider's name

### ISSUE THREAD

**Issue by TheBits** [dstackai/dstack#981]
### dstack version

0.16.2

### Python version

3.11.8

### Host OS

Arch Linux

### Host Arch

x86_64

### What happened?

For example, the command `dstack run . -f task.dstack.yaml -b lamda` shows stack trace.

### CLI logs

```shell
❯ dstack run . -f task.dstack.yaml  -b lamda
Traceback (most recent call last):
  File "/home/thebits/dstack/simple/.direnv/python-3.11/bin/dstack", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/thebits/dstack/simple/.direnv/python-3.11/lib/python3.11/site-packages/dstack/_internal/cli/main.py", line 67, in main
    args.func(args)
  File "/home/thebits/dstack/simple/.direnv/python-3.11/lib/python3.11/site-packages/dstack/_internal/cli/commands/run.py", line 113, in _command
    run_plan = self.api.runs.get_plan(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thebits/dstack/simple/.direnv/python-3.11/lib/python3.11/site-packages/dstack/api/_public/runs.py", line 429, in get_plan
    profile = Profile(
              ^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Profile
backends -> 0
  value is not a valid enumeration member; permitted: 'aws', 'azure', 'cudo', 'datacrunch', 'dstack', 'gcp', 'kubernetes', 'lambda', 'local', 'remote', 'nebius', 'tensordock', 'vastai' (type=type_error.enum; enum_values=[<BackendType.AWS: 'aws'>, <BackendType.AZURE: 'azure'>, <BackendType.CUDO: 'cudo'>, <BackendType.DATACRUNCH: 'datacrunch'>, <BackendType.DSTACK: 'dstack'>, <BackendType.GCP: 'gcp'>, <BackendType.KUBERNETES: 'kubernetes'>, <BackendType.LAMBDA: 'lambda'>, <BackendType.LOCAL: 'local'>, <BackendType.REMOTE: 'remote'>, <BackendType.NEBIUS: 'nebius'>, <BackendType.TENSORDOCK: 'tensordock'>, <BackendType.VASTAI: 'vastai'>])
```
```


### Server logs

_No response_

### Runner logs

_No response_

### Additional Information

_No response_

**Comment by r4victor** [comment]
I wouldn't consider it a bug. This is an expected behavior. Any bad values specified in profiles.yml would lead to ValidationError from pydantic. The message is quite clear.

**Comment by peterschmidt85** [comment]
This issue is stale because it has been open for 30 days with no activity.

**Comment by peterschmidt85** [comment]
This issue was closed because it has been inactive for 14 days since being marked as stale.
