### ISSUE TITLE
[Bug]: It's not possible to configure projects other than `main` via `~/.dstack/server/config.yml`

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#991]
Steps to reproduce:

1. Define a project in `~/.dstack/server/config.yml` that has a name different from `main`
2. Run `dstack server`

```
ERROR:    Traceback (most recent call last):
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/Users/cheptsov/miniforge3/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/dstack/src/dstack/_internal/server/app.py", line 88, in lifespan
    await server_config_manager.apply_config(session=session)
  File "/Users/cheptsov/dstack/src/dstack/_internal/server/services/config.py", line 188, in apply_config
    project = await projects_services.get_project_model_by_name_or_error(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/dstack/src/dstack/_internal/server/services/projects.py", line 229, in get_project_model_by_name_or_error
    return res.scalar_one()
           ^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 1472, in scalar_one
    return self._only_one_row(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/cheptsov/miniforge3/lib/python3.11/site-packages/sqlalchemy/engine/result.py", line 760, in _only_one_row
    raise exc.NoResultFound(
sqlalchemy.exc.NoResultFound: No row was found when one was required
```

**Comment by peterschmidt85** [comment]
Released in `0.16.3` ([Discord link](https://discord.com/channels/1106906313969123368/1163422692226113538/1217800685752422450))
